version: "3.1"

services:
  mongo:
    container_name: "${APP_NAME}_mongodb"
    image: mongo:latest
    restart: always
    volumes:
      - ./docker/data/mongodb/:/data/db:rw
    environment:
      - "MONGO_INITDB_DATABASE=${DB_NAME}"
      - "MONGO_INITDB_ROOT_USERNAME=${DB_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}"
    ports:
      - "${DB_PORT}:27017"
    command: mongod
